name: Feature Request
description: Suggest an idea for improving gymkhana
labels: 'enhancement'
body:
  - type: textarea
    id: description
    attributes:
      label: Is your proposal related to a problem?
      description: Please provide a clear and concise description of what the problem is.
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: |
        Please provide a clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternative-solution
    attributes:
      label: Describe alternatives you've considered
      description: |
        Please let us know about other solutions you've tried or researched.
    validations:
      required: false
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: |
         Is there anything else you can add about the proposal?
         You might want to link to related issues here, if you haven't already.
