# Generated by Django 4.0.5 on 2022-08-16 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api_clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Coordinator', 'Coordinator'), ('Co-Coordinator', 'Co-Coordinator'), ('Core member', 'Core member'), ('Faculty Incharge', 'Faculty Incharge'), ('Convener', 'Convener'), ('Co-convener', 'Co-convener'), ('Counsellor', ' Counsellor'), ('Associate- Counsellor', 'Associate- Counsellor')], max_length=30)),
                ('assigned_at', models.DateField()),
                ('active', models.BooleanField(default=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api_clubs.club')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
