# Generated by Django 4.0.5 on 2022-08-16 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_clubs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('starts_at', models.DateField()),
                ('ends_at', models.DateField()),
                ('registration_required', models.BooleanField(default=False)),
                ('image_url', models.URLField(max_length=500)),
                ('registration_approval_required', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=500)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='api_clubs.club')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
